apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: ems-timescaledb
    url: timescaledb:5432
    user: admin
    secureJsonData:
      password: ems123456
    jsonData:
      database: ems
      sslmode: disable
      timescaledb: true
    editable: false
